// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneeChan.Database;

namespace OneeChan.Migrations
{
    [DbContext(typeof(OneeChanEntities))]
    partial class OneeChanEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("OneeChan.Database.Entities.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseKeeperSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServerSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseKeeperSettingsId");

                    b.HasIndex("ServerSettingsId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("OneeChan.Database.Entities.HouseKeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AutoCategoryChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AutoVoiceChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HouseKeeper");
                });

            modelBuilder.Entity("OneeChan.Database.Entities.ServerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char?>("Prefix")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("OneeChan.Database.Entities.Guild", b =>
                {
                    b.HasOne("OneeChan.Database.Entities.HouseKeeper", "HouseKeeperSettings")
                        .WithMany()
                        .HasForeignKey("HouseKeeperSettingsId");

                    b.HasOne("OneeChan.Database.Entities.ServerSettings", "ServerSettings")
                        .WithMany()
                        .HasForeignKey("ServerSettingsId");
                });
#pragma warning restore 612, 618
        }
    }
}
